import type { Athlete, Achievement } from './api'

const makeAchievements = (years: number[], medals: Array<'gold' | 'silver' | 'bronze' | 'none'>, competitions: string[]): Achievement[] =>
  years.map((year, i) => ({
    id: `ach-${year}-${i}`,
    athlete_id: '',
    year,
    competition: competitions[i] ?? 'אליפות ישראל',
    medal: medals[i] ?? 'none',
    description: '',
    is_olympic: medals[i] !== 'none' && year >= 2020,
  }))

export const DEMO_ATHLETES: Athlete[] = [
  {
    id: 'a1',
    full_name: 'דיאנה סוסונוב',
    sport: 'התעמלות אמנותית',
    age: 26,
    city: 'תל אביב',
    status: 'olympic',
    gender: 'female',
    bio: 'התחלתי להתעמל בגיל 6 מאז זה הבית שלי. הדרך מלאה באתגרים, עבודה קשה והרבה אמונה בעצמי. המטרה שלי להלהיב לטודים ולייצג את ישראל בגאווה.',
    values: ['מצוינות', 'התמדה', 'נחישות'],
    avatar_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2018, 2019, 2020, 2021, 2022, 2023, 2024],
      ['silver', 'gold', 'bronze', 'gold', 'silver', 'gold', 'gold'],
      ['אליפות ישראל', 'מכביה', 'אליפות אירופה', 'אולימפיאדה טוקיו', 'אליפות עולם', 'משחקים אירופאים', 'מדליה כסף גביע עולם']
    ),
    sponsors: [{ id: 's1', athlete_id: 'a1', company_name: 'Samsung', logo_url: '', start_date: '2023-01-01', is_active: true }],
    coaches: [{ name: 'אירה וגנדר', role: 'מאמנת ראשית' }],
  },
  {
    id: 'a2',
    full_name: 'יונתן כהן',
    sport: 'קייקינג',
    age: 28,
    city: 'חיפה',
    status: 'olympic',
    gender: 'male',
    bio: 'הנהר הוא הבית שלי. 18 שנות אימונים יומיומיים הביאו אותי לייצג את ישראל בגביעי עולם ואולימפיאדה.',
    values: ['מחויבות', 'עמידה באתגרים', 'ספורטיביות'],
    avatar_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2019, 2020, 2021, 2022, 2023, 2024],
      ['bronze', 'none', 'silver', 'gold', 'silver', 'gold'],
      ['אליפות אסיה', 'נבחרת ישראל', 'גביע עולם', 'אליפות עולם', 'מכביה', 'אולימפיאדה פריז']
    ),
    sponsors: [],
    coaches: [{ name: 'מיכאל לוי', role: 'מאמן ראשי' }],
  },
  {
    id: 'a3',
    full_name: 'אנסטסיה גורבנקו',
    sport: 'שחייה',
    age: 21,
    city: 'חולון',
    status: 'olympic',
    gender: 'female',
    bio: 'שחיינית תחרותית שמייצגת את ישראל בזירה הבינלאומית. מתמחה בגב ומדרדפת אחרי שיא אישי בכל תחרות.',
    values: ['שיפור מתמיד', 'אמוץ האתגר', 'ניצחון פנימי'],
    avatar_url: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2020, 2021, 2022, 2023, 2024],
      ['none', 'silver', 'silver', 'bronze', 'silver'],
      ['אליפות ישראל', 'אליפות אירופה', 'גביע עולם', 'מכביה', 'אולימפיאדה פריז']
    ),
    sponsors: [],
    coaches: [{ name: 'דב שפירא', role: 'מאמן בכיר' }],
  },
  {
    id: 'a4',
    full_name: 'עומר גולדשטיין',
    sport: 'אופניים',
    age: 25,
    city: 'ירושלים',
    status: 'olympic',
    gender: 'male',
    bio: 'רוכב על שדות ומסלולים בכל העולם. ייצגתי את ישראל בשלוש אולימפיאדות וממשיך להתמקד בפריז 2028.',
    values: ['עקשנות', 'פוקוס', 'ניצחון'],
    avatar_url: 'https://images.unsplash.com/photo-1534787238916-9ba6764efd4f?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2018, 2019, 2021, 2022, 2023, 2024],
      ['bronze', 'silver', 'gold', 'silver', 'gold', 'bronze'],
      ['גביע עולם', 'אליפות אסיה', 'אולימפיאדה טוקיו', 'גביע עולם', 'אליפות עולם', 'אולימפיאדה פריז']
    ),
    sponsors: [],
    coaches: [{ name: 'רון קדם', role: 'מאמן אישי' }],
  },
  {
    id: 'a5',
    full_name: 'ארטיום דולגפיאט',
    sport: 'התעמלות מכשירים',
    age: 27,
    city: 'ראשון לציון',
    status: 'olympic',
    gender: 'male',
    bio: 'מתעמל בינלאומי שייצג את ישראל בשלוש אולימפיאדות. מומחה בקרקע ובעיגול.',
    values: ['מדויקות', 'גמישות', 'עמידה בלחץ'],
    avatar_url: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2019, 2020, 2021, 2022, 2023, 2024],
      ['silver', 'gold', 'gold', 'silver', 'gold', 'silver'],
      ['אליפות עולם', 'אולימפיאדה טוקיו', 'גביע עולם', 'אליפות אירופה', 'אולימפיאדה פריז', 'מכביה']
    ),
    sponsors: [],
    coaches: [{ name: 'ולנטין מוראב', role: 'מאמן ראשי' }],
  },
  {
    id: 'a6',
    full_name: 'שירה ראשוני',
    sport: "גרו",
    age: 20,
    city: 'נתניה',
    status: 'hopeful',
    gender: 'female',
    bio: 'ג\'ודוקאית צעירה עם פוטנציאל עצום. אלופת ישראל 3 שנים ברצף ושמה עיניים על הזהב האולימפי.',
    values: ['כבוד', 'משמעת', 'חתירה למצוינות'],
    avatar_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2021, 2022, 2023, 2024],
      ['gold', 'gold', 'silver', 'gold'],
      ['אליפות ישראל', 'אליפות ישראל', 'אליפות אירופה U23', 'אליפות ישראל']
    ),
    sponsors: [],
    coaches: [{ name: 'גיא שחם', role: 'מאמן לאומי' }],
  },
  {
    id: 'a7',
    full_name: 'דניאל צוקרמן',
    sport: 'טניס',
    age: 24,
    city: 'הרצליה',
    status: 'olympic',
    gender: 'male',
    bio: 'שחקן טניס ישראלי המדורג ב-TOP 100 בעולם. אוהב לשחק על קרקע אדומה ומייצג את ישראל בגביע דייוויס.',
    values: ['אסטרטגיה', 'קור רוח', 'מנטליות אלוף'],
    avatar_url: 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2019, 2021, 2022, 2023, 2024],
      ['none', 'bronze', 'silver', 'silver', 'gold'],
      ['מדורג ATP 200', 'גביע דייוויס', 'מדורג ATP 120', 'מדורג ATP 85', 'אולימפיאדה פריז']
    ),
    sponsors: [],
    coaches: [{ name: 'ניר צוקרמן', role: 'מאמן אישי' }],
  },
  {
    id: 'a8',
    full_name: 'קטי ספיציקוב',
    sport: 'שייט',
    age: 22,
    city: 'חיפה',
    status: 'olympic',
    gender: 'female',
    bio: 'גולשת ומפרשנית המייצגת את ישראל בתחרויות בינלאומיות. אלופת ישראל פעמיים וחצתה ים בגיל 19.',
    values: ['אומץ', 'חירות', 'חדשנות'],
    avatar_url: 'https://images.unsplash.com/photo-1531053270060-6643c8e70e8f?w=400&q=80',
    is_verified: true,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2020, 2021, 2022, 2023, 2024],
      ['silver', 'gold', 'bronze', 'silver', 'gold'],
      ['אליפות ישראל', 'גביע עולם U23', 'אליפות אירופה', 'אליפות עולם', 'אולימפיאדה פריז']
    ),
    sponsors: [],
    coaches: [{ name: 'עמי שפר', role: 'מאמן ראשי' }],
  },
  {
    id: 'a9',
    full_name: 'נועה לביא',
    sport: 'אתלטיקה',
    age: 19,
    city: 'באר שבע',
    status: 'hopeful',
    gender: 'female',
    bio: 'רצה צעירה עם פוטנציאל אדיר. שיאנית ישראל ל-400 מטר בגיל 18. חולמת על מדליה אולימפית.',
    values: ['מהירות', 'שאיפה', 'ביטחון עצמי'],
    avatar_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&q=80',
    is_verified: false,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2022, 2023, 2024],
      ['gold', 'gold', 'silver'],
      ['אליפות ישראל נוער', 'שיאנית ישראל 400מ', 'אליפות אירופה U20']
    ),
    sponsors: [],
    coaches: [{ name: 'חיים גד', role: 'מאמן ארצי' }],
  },
  {
    id: 'a10',
    full_name: 'אביתר כץ',
    sport: 'קייקינג',
    age: 23,
    city: 'תל אביב',
    status: 'hopeful',
    gender: 'male',
    bio: 'קייקאי צעיר ומשתפר מתחרות לתחרות. עקב אחר אלוף העולם מהצד ועכשיו הוא מתמודד מולו.',
    values: ['מוטיבציה', 'צמיחה', 'ניצחון'],
    avatar_url: 'https://images.unsplash.com/photo-1551958219-acbc595b6c6f?w=400&q=80',
    is_verified: false,
    is_published: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    achievements: makeAchievements(
      [2021, 2022, 2023, 2024],
      ['none', 'bronze', 'silver', 'silver'],
      ['אליפות ישראל', 'אליפות אירופה U23', 'גביע עולם', 'אליפות עולם U23']
    ),
    sponsors: [],
    coaches: [{ name: 'אריה גל', role: 'מאמן אישי' }],
  },
]
